FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Whogoesthere

It's Whogoesthere.

## Event [/event/{id}]
### Get One Event [GET]
+ Response 200 (application/json)

        {
            "name": "String",
            "description": "String",
            "location": "String",
            "start_time": "2015-08-05T08:40:51.620Z",
            "end_time": "2015-08-05T08:40:51.620Z",
            "creator": {
                "email": "mail@mail.com",
                "name": "Abtin",
            },
            "id": "12789rwahsjdkln",
        }
### Update an Event [PUT]
+ Request (application/json)

        {
            "name": "String",
            "description": "String",
            "location": "String",
            "start_time": "2015-08-05T08:40:51.620Z",
            "end_time": "2015-08-05T08:40:51.620Z",
        }

+ Response 201 (application/json)

        {
            "name": "String",
            "description": "String",
            "location": "String",
            "start_time": "2015-08-05T08:40:51.620Z",
            "end_time": "2015-08-05T08:40:51.620Z",
            "creator": {
                "email": "mail@mail.com",
                "name": "Abtin",
            },
            "id": "12789rwahsjdkln",
        }

### Delete an Event [DELETE]
+ Response 200 (application/json)


## Events Collection [/event]

### List All Events [GET]

+ Response 200 (application/json)

        [
            {
                "name": "String",
                "description": "String",
                "location": "String",
                "start_time": "2015-08-05T08:40:51.620Z",
                "end_time": "2015-08-05T08:40:51.620Z",
                "creator": {
                    "email": "mail@mail.com",
                    "name": "Abtin",
                },
                "id": "12789rwahsjdkln",
            }
        ]

### Create a New Event [POST]

You can create an event.

+ Request (application/json)

        {
            "name": "String",
            "description": "String",
            "location": "String",
            "start_time": "2015-08-05T08:40:51.620Z",
            "end_time": "2015-08-05T08:40:51.620Z",
        }

+ Response 201 (application/json)

        {
            "name": "String",
            "description": "String",
            "location": "String",
            "start_time": "2015-08-05T08:40:51.620Z",
            "end_time": "2015-08-05T08:40:51.620Z",
            "creator": {
                "email": "mail@mail.com",
                "name": "Abtin",
            },
            "id": "12789rwahsjdkln",
        }

## Comments Collection [/event/{id}/comment/]

### Get all Comments [GET]

+ Response 200 (application/json)

        [
            {
                "created_at": "2015-08-05T08:40:51.620Z",
                "body": "String",
                "author": {
                    "email": "mail@mail.com",
                    "name": "Abtin",
                },
            }
        ]

### Post Comment [POST]

+ Response 200 (application/json)

        {
            "body": "String",e
        }

## RSVP [/event/${id}/rsvp/]

### Get event RSVPs [GET]
+ Response 200 (application/json)

        {
            "yes": 2,
            "no": 2,
            "maybe": 2,
            "no_response": 2,
        }

## Invitation [/invitation/{id}]

### Respond to an event [POST]


+ Request (application/json)

        {
          "response": yes, no, maybe, no-response (enum),
        }
+ Response 200 (application/json)


## Invitations Collection [/invitation/]

### Get invitations [GET]

+ Response 200 (application/json)

        [
            {
                "event_id": "asdfjkl123i912",
                "response": yes, no, maybe, no-response (enum),
            }
        ]